name: MurderMysteryShowdown
version: 1.0.0
main: com.mineblock64.murdermysteryshowdown.MurderMysteryShowdown
authors: [MineBlock64]
description: Murder Mystery Showdown gamemode.
website: https://developer64.com
